import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontSize: 12,
    fontFamily: "Helvetica",
    backgroundColor: "#ffffff",
  },
  header: {
    marginBottom: 50,
    textAlign: "center",
    borderBottom: "3 solid #2563eb",
    paddingBottom: 25,
  },
  title: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#1f2937",
    marginBottom: 15,
  },
  subtitle: {
    fontSize: 18,
    color: "#6b7280",
    marginBottom: 10,
  },
  experienceCard: {
    marginBottom: 30,
    flexDirection: "row",
  },
  // Liseré bleu sur le côté
  timelineContainer: {
    width: 20,
    alignItems: "center",
    marginRight: 15,
    position: "relative",
  },
  timelineLine: {
    width: 2,
    backgroundColor: "#2563eb",
    flex: 1,
  },
  timelineCircle: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#2563eb",
    position: "absolute",
    top: 5,
    left: 5,
  },
  // Contenu principal
  experienceContent: {
    flex: 1,
  },
  experienceTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1f2937",
    marginBottom: 6,
    breakInside: "avoid",
    borderBottom: "2 solid #2563eb",
    paddingBottom: 8,
  },
  company: {
    fontSize: 12,
    color: "#6b7280",
    fontWeight: "600",
    marginBottom: 10,
    textTransform: "uppercase",
    letterSpacing: 1,
  },

  description: {
    fontSize: 10,
    lineHeight: 1.6,
    color: "#374151",
    marginBottom: 15,
    whiteSpace: "pre-line",
    textAlign: "justify",
    breakInside: "avoid",
  },
  technologies: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  techBadge: {
    backgroundColor: "#2563eb",
    color: "white",
    padding: "6 12",
    borderRadius: 6,
    fontSize: 11,
    marginRight: 8,
    marginBottom: 8,
    fontWeight: "600",
    boxShadow: "0 1 3 rgba(0,0,0,0.2)",
  },
  typeBadge: {
    backgroundColor: "#059669",
    color: "white",
    padding: "4 8",
    borderRadius: 5,
    fontSize: 10,
    marginLeft: 10,
  },
  devBadge: {
    backgroundColor: "#2563eb",
    color: "white",
    padding: "5 12",
    borderRadius: 5,
    fontSize: 10,
    fontWeight: "bold",
    marginBottom: 12,
  },
  periodsSection: {
    marginTop: 10,
  },
  periodItem: {
    marginBottom: 8,
    alignItems: "flex-end",
    flexDirection: "column",
  },
  periodDescription: {
    marginBottom: 5,
    padding: 5,
    marginRight: 10,
  },
  periodHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  periodTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#1f2937",
    flexWrap: "nowrap",
    whiteSpace: "nowrap",
    breakInside: "avoid",
    borderBottom: "1 solid #e5e7eb",
    paddingBottom: 5,
    flex: 1,
  },
  periodDates: {
    fontSize: 11,
    color: "#6b7280",
    fontWeight: "500",
    flexShrink: 0,
    textAlign: "right",
  },
  periodContent: {
    fontSize: 10,
    lineHeight: 1.6,
    color: "#374151",
    whiteSpace: "pre-line",
    textAlign: "justify",
    breakInside: "avoid",
  },
  pageNumber: {
    position: "absolute",
    bottom: 20,
    left: 50,
    right: 50,
    textAlign: "right",
    fontSize: 12,
    color: "#6b7280",
  },

  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1f2937",
    marginBottom: 15,
    borderBottom: "1 solid #e5e7eb",
    paddingBottom: 10,
  },
});
